### ISSUE TITLE
Add ability for more tow trucks.

### ISSUE THREAD

**Issue by OhTanoshi** [xander1998/towtruck#2]
More of a enhancement that's super simple to do.

Just allow config to handle trucks and offset of the attached vehicle.

When i have time i could fork and add this.

Other then that its actually a really good script that seems to be already better then the other tow scripts. especially when the issues of not allowing to retrieve a second tow truck if the first is destroyed is fixed

**Comment by xander1998** [comment]
You want multiple trucks but how would the multiple trucks work? Menu Based? Chat Based? Ability to spawn the truck and use left and right arrows to go through the options and spawn it?

**Comment by OhTanoshi** [comment]
the easiest would be a menu but the option to use left and right arrows would be something really cool to see.
